name: Releases Source

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependent
        run: |
          make dependent
      - name: Checkout
        run: |
          make $(basename ${GITHUB_REF})
      - name: Public source
        run: |
          GH_TOKEN="${GH_TOKEN:-${{ secrets.GITHUB_TOKEN }}}"  make public-source
